export const LANDING_PAGE_HEADER_HEIGHT = 80;
export const LANDING_PAGE_HEADER_ORDER = 2;

export const LANDING_PAGE_XL_CONTAINER_WIDTH = 1560;
export const MAIN_LAYOUT_FOOTER_BG = '#002579';
export const MAIN_LAYOUT_HEADER_BG = '#002c8f';
